#!/bin/bash
############################
# .make.sh
# This script creates symlinks from the home directory to any desired vimfiles in ~/vimfiles
############################

########## Variables

dir=~/vimfiles                    # vimfiles directory
olddir=~/vimfiles_old             # old vimfiles backup directory
files="vim vimrc gvimrc"    # list of files/folders to symlink in homedir

##########

# create vimfiles_old in homedir
echo "Creating $olddir for backup of any existing vimfiles in ~"
mkdir -p $olddir
echo "...done"

# change to the vimfiles directory
echo "Changing to the $dir directory"
cd $dir
echo "...done"

# move any existing vimfiles in homedir to vimfiles_old directory, then create symlinks 
for file in $files; do
    echo "Moving any existing vimfiles from ~ to $olddir"
    mv ~/.$file ~/vimfiles_old/
    echo "Creating symlink to $file in home directory."
    ln -s $dir/$file ~/.$file
done


mkdir ~/.tmp
